apiVersion: apps/v1
kind: Deployment
metadata:
  name: bnpl-order-service
  labels:
    app: bnpl-order-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bnpl-order-service
  template:
    metadata:
      labels:
        app: bnpl-order-service
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /actuator/prometheus
        prometheus.io/port: "9002"
    spec:
      containers:
        - name: bnpl-order-service
          image: bnpl-order-service
          imagePullPolicy: IfNotPresent
          lifecycle:
            preStop:
              exec:
                command: [ "sh", "-c", "sleep 5" ]
          ports:
            - containerPort: 9002
          env:
            - name: BPL_JVM_THREAD_COUNT
              value: "50"
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 9002
            initialDelaySeconds: 10
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 9002
            initialDelaySeconds: 5
            periodSeconds: 15
          volumeMounts:
            - name: bnpl-order-config-volume
              mountPath: /workspace/config
      volumes:
        - name: bnpl-order-config-volume
          configMap:
            name: bnpl-order-config